const items = [
  {
    SKU: "BIKE001",
    Name: "Mountain Bike",
    Price: 899.99,
    Category: "Bikes",
    Quantity: 5,
  },
  {
    SKU: "BIKE002",
    Name: "Road Bike",
    Price: 1299.99,
    Category: "Bikes",
    Quantity: 3,
  },
  {
    SKU: "BIKE003",
    Name: "Hybrid Bike",
    Price: 699.99,
    Category: "Bikes",
    Quantity: 7,
  },
  {
    SKU: "BIKE004",
    Name: "Kids' Bike",
    Price: 299.99,
    Category: "Bikes",
    Quantity: 10,
  },
  {
    SKU: "BIKE005",
    Name: "BMX Bike",
    Price: 399.99,
    Category: "Bikes",
    Quantity: 8,
  },
  {
    SKU: "ACCS001",
    Name: "Helmet",
    Price: 49.99,
    Category: "Accessories",
    Quantity: 15,
  },
  {
    SKU: "ACCS002",
    Name: "Bike Lights",
    Price: 29.99,
    Category: "Accessories",
    Quantity: 20,
  },
  {
    SKU: "ACCS003",
    Name: "Bike Lock",
    Price: 39.99,
    Category: "Accessories",
    Quantity: 12,
  },
  {
    SKU: "ACCS004",
    Name: "Bike Pump",
    Price: 14.99,
    Category: "Accessories",
    Quantity: 25,
  },
  {
    SKU: "ACCS005",
    Name: "Water Bottle",
    Price: 9.99,
    Category: "Accessories",
    Quantity: 30,
  },
  {
    SKU: "ACCS006",
    Name: "Bike Rack",
    Price: 79.99,
    Category: "Accessories",
    Quantity: 6,
  },
  {
    SKU: "ACCS007",
    Name: "Bike Basket",
    Price: 24.99,
    Category: "Accessories",
    Quantity: 18,
  },
  {
    SKU: "APPA001",
    Name: "Cycling Jersey",
    Price: 59.99,
    Category: "Apparel",
    Quantity: 10,
  },
  {
    SKU: "APPA002",
    Name: "Cycling Shorts",
    Price: 49.99,
    Category: "Apparel",
    Quantity: 12,
  },
  {
    SKU: "APPA003",
    Name: "Cycling Gloves",
    Price: 24.99,
    Category: "Apparel",
    Quantity: 15,
  },
  {
    SKU: "APPA004",
    Name: "Cycling Shoes",
    Price: 129.99,
    Category: "Apparel",
    Quantity: 4,
  },
  {
    SKU: "ACCS008",
    Name: "Bike Repair Kit",
    Price: 19.99,
    Category: "Accessories",
    Quantity: 20,
  },
  {
    SKU: "ACCS009",
    Name: "Bike Chain",
    Price: 12.99,
    Category: "Accessories",
    Quantity: 30,
  },
  {
    SKU: "ACCS010",
    Name: "Bike Tires",
    Price: 39.99,
    Category: "Accessories",
    Quantity: 8,
  },
  {
    SKU: "ACCS011",
    Name: "Inner Tubes",
    Price: 7.99,
    Category: "Accessories",
    Quantity: 25,
  },
];

module.exports = { items };
