const items = [
  {
    SKU: "BIKE001",
    Name: "Mountain Bike",
    Price: 899.99,
    Category: "Bikes",
    Quantity: 5,
  },
  {
    SKU: "BIKE002",
    Name: "Road Bike",
    Price: 1299.99,
    Category: "Bikes",
    Quantity: 3,
  },
  {
    SKU: "BIKE003",
    Name: "Hybrid Bike",
    Price: 699.99,
    Category: "Bikes",
    Quantity: 7,
  },
  {
    SKU: "BIKE004",
    Name: "Kids' Bike",
    Price: 299.99,
    Category: "Bikes",
    Quantity: 10,
  },
  {
    SKU: "BIKE005",
    Name: "BMX Bike",
    Price: 399.99,
    Category: "Bikes",
    Quantity: 8,
  },
  {
    SKU: "ACCS001",
    Name: "Helmet",
    Price: 49.99,
    Category: "Accessories",
    Quantity: 15,
  },
  {
    SKU: "ACCS002",
    Name: "Bike Lights",
    Price: 29.99,
    Category: "Accessories",
    Quantity: 20,
  },
  {
    SKU: "ACCS003",
    Name: "Bike Lock",
    Price: 39.99,
    Category: "Accessories",
    Quantity: 12,
  },
  {
    SKU: "ACCS004",
    Name: "Bike Pump",
    Price: 14.99,
    Category: "Accessories",
    Quantity: 25,
  },
  {
    SKU: "ACCS005",
    Name: "Water Bottle",
    Price: 9.99,
    Category: "Accessories",
    Quantity: 30,
  },
  {
    SKU: "ACCS006",
    Name: "Bike Rack",
    Price: 79.99,
    Category: "Accessories",
    Quantity: 6,
  },
  {
    SKU: "ACCS007",
    Name: "Bike Basket",
    Price: 24.99,
    Category: "Accessories",
    Quantity: 18,
  },
  {
    SKU: "APPA001",
    Name: "Cycling Jersey",
    Price: 59.99,
    Category: "Apparel",
    Quantity: 10,
  },
  {
    SKU: "APPA002",
    Name: "Cycling Shorts",
    Price: 49.99,
    Category: "Apparel",
    Quantity: 12,
  },
  {
    SKU: "APPA003",
    Name: "Cycling Gloves",
    Price: 24.99,
    Category: "Apparel",
    Quantity: 15,
  },
  {
    SKU: "APPA004",
    Name: "Cycling Shoes",
    Price: 129.99,
    Category: "Apparel",
    Quantity: 4,
  },
  {
    SKU: "ACCS008",
    Name: "Bike Repair Kit",
    Price: 19.99,
    Category: "Accessories",
    Quantity: 20,
  },
  {
    SKU: "ACCS009",
    Name: "Bike Chain",
    Price: 12.99,
    Category: "Accessories",
    Quantity: 30,
  },
  {
    SKU: "ACCS010",
    Name: "Bike Tires",
    Price: 39.99,
    Category: "Accessories",
    Quantity: 8,
  },
  {
    SKU: "ACCS011",
    Name: "Inner Tubes",
    Price: 7.99,
    Category: "Accessories",
    Quantity: 25,
  },
];

const carItems = [
  {
    SKU: "CAR001",
    Name: "Engine Oil",
    Price: 29.99,
    Category: "Engine",
    Quantity: 100,
  },
  {
    SKU: "CAR002",
    Name: "Brake Pads",
    Price: 59.99,
    Category: "Brakes",
    Quantity: 50,
  },
  {
    SKU: "CAR003",
    Name: "Spark Plugs",
    Price: 19.99,
    Category: "Engine",
    Quantity: 75,
  },
  {
    SKU: "CAR004",
    Name: "Air Filter",
    Price: 24.99,
    Category: "Engine",
    Quantity: 60,
  },
  {
    SKU: "CAR005",
    Name: "Fuel Filter",
    Price: 16.99,
    Category: "Engine",
    Quantity: 80,
  },
  {
    SKU: "CAR006",
    Name: "Battery",
    Price: 99.99,
    Category: "Electrical",
    Quantity: 30,
  },
  {
    SKU: "CAR007",
    Name: "Headlights",
    Price: 79.99,
    Category: "Lighting",
    Quantity: 40,
  },
  {
    SKU: "CAR008",
    Name: "Taillights",
    Price: 69.99,
    Category: "Lighting",
    Quantity: 50,
  },
  {
    SKU: "CAR009",
    Name: "Tires",
    Price: 129.99,
    Category: "Wheels & Tires",
    Quantity: 20,
  },
  {
    SKU: "CAR010",
    Name: "Rims",
    Price: 299.99,
    Category: "Wheels & Tires",
    Quantity: 15,
  },
  {
    SKU: "CAR011",
    Name: "Windshield Wipers",
    Price: 14.99,
    Category: "Exterior",
    Quantity: 100,
  },
  {
    SKU: "CAR012",
    Name: "Floor Mats",
    Price: 39.99,
    Category: "Interior",
    Quantity: 80,
  },
  {
    SKU: "CAR013",
    Name: "Steering Wheel Cover",
    Price: 19.99,
    Category: "Interior",
    Quantity: 60,
  },
  {
    SKU: "CAR014",
    Name: "Seat Covers",
    Price: 59.99,
    Category: "Interior",
    Quantity: 40,
  },
  {
    SKU: "CAR015",
    Name: "Car Wash Kit",
    Price: 24.99,
    Category: "Maintenance",
    Quantity: 120,
  },
  {
    SKU: "CAR016",
    Name: "First Aid Kit",
    Price: 19.99,
    Category: "Safety",
    Quantity: 50,
  },
  {
    SKU: "CAR017",
    Name: "Fire Extinguisher",
    Price: 29.99,
    Category: "Safety",
    Quantity: 30,
  },
  {
    SKU: "CAR018",
    Name: "Car Jump Starter",
    Price: 49.99,
    Category: "Electrical",
    Quantity: 20,
  },
  {
    SKU: "CAR019",
    Name: "GPS Navigation System",
    Price: 199.99,
    Category: "Electronics",
    Quantity: 10,
  },
  {
    SKU: "CAR020",
    Name: "Rearview Camera",
    Price: 99.99,
    Category: "Electronics",
    Quantity: 15,
  },
];

module.exports = { items, carItems };
